- hosts: 127.0.0.1
  user: vagrant
  connection: local
  vars:
    pyenv_install_dir: /home/vagrant/.pyenv
    env_setting_file: /home/vagrant/.bashrc
    zone: Asia/Tokyo
    zoneinfo_path: /usr/share/zoneinfo/Asia/Tokyo

  tasks:
    - name: install Development tooles
      become: yes
      yum: name={{ item }} state=installed
      with_items:
        #- epol-release
        - nano
        - git
        - curl
        - openssl-devel
        - make
        - gcc-c++
        - zlib
        - zlib-devel
        - curl-devel
        - nginx
        - patch
        - readline-devel
        - sqlite-devel
        - libxml2-devel
        - libxslt-devel
        - bzip2-devel
        - python-devel
        - libsemanage-python
        - libselinux-python
        - gdbm
        - gdbm-devel
        #- numpy
        #- scipy
        #- python-matplotlib
        #- ipython
        #- python-pandas

    - name: set zone to /etc/sysconfig/clock
      become: yes      
      replace: >
        dest=/etc/sysconfig/clock
        regexp='^ZONE=\"UTC\"'
        replace='ZONE="{{zone}}"'
    - name: set localtime
      become: yes
      file: >
        src={{zoneinfo_path}}
        dest=/etc/localtime
        state=link
        force=yes

    - name: git clone pyenv 
      git: repo=git://github.com/yyuu/pyenv.git
           dest={{ pyenv_install_dir }} accept_hostkey=yes

    - name: copy bashrc
      copy: src=/home/vagrant/work/.bashrc dest=/home/vagrant/.bashrc backup=yes

    - name: install anaconda2
      shell: |
          source ~/.bashrc
          pyenv install anaconda2-2.5.0
          pyenv rehash
          pyenv global anaconda2-2.5.0
          
